### ISSUE TITLE
Todo: v0.3

### ISSUE THREAD

**Issue by DannyvanderJagt** [DannyvanderJagt/rocket-engine#1]
Improvement list for v0.3:

**Features**
- [x] Introduce `.rocket` settings file
- [x] Read the settings from `.rocket` file instead of using the `initialize` function.
- [x] Throw errors when there is no error listener/wildcard listener.

**Bugs**
- [x] Events are fired before there is a change to listen for the client. **Includes error events.**
